export enum OnboardingStatus {
  PENDING_STORE_CONFIG = 'PENDING_STORE_CONFIG',
  PENDING_STORE_ROLE = 'PENDING_STORE_ROLE',
  PENDING_TEAM_CONFIG = 'PENDING_TEAM_CONFIG',
  COMPLETED = 'COMPLETED',
}
