export enum OnboardingStatus {
  PENDING_TENANT_CONFIG = 'PENDING_TENANT_CONFIG',
  PENDING_PLAN_SELECTION = 'PENDING_PLAN_SELECTION',
  PENDING_STORE_CONFIG = 'PENDING_STORE_CONFIG',
  PENDING_STORE_ROLE = 'PENDING_STORE_ROLE',
  PENDING_TEAM_CONFIG = 'PENDING_TEAM_CONFIG',
  COMPLETED = 'COMPLETED',
}