export const NotificationType = {
  STORE_CONNECTION_KEY_RECEIVED: 'STORE_CONNECTION_KEY_RECEIVED',
  STORE_CONNECTION_ESTABLISHED: 'STORE_CONNECTION_ESTABLISHED',
  STORE_CONNECTION_REVOKED: 'STORE_CONNECTION_REVOKED',
  SYNC_BATCH_COMPLETED: 'SYNC_BATCH_COMPLETED',
  INITIAL_SYNC_COMPLETED: 'INITIAL_SYNC_COMPLETED',
  SYNC_ERROR: 'SYNC_ERROR',
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_ARCHIVED: 'PRODUCT_ARCHIVED',
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_UPDATED: 'ORDER_UPDATED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_FULFILLED: 'ORDER_FULFILLED',
  ORDER_PAID: 'ORDER_PAID',
  ORDER_REFUNDED: 'ORDER_REFUNDED',
  PAYOUT_PENDING: 'PAYOUT_PENDING',
  INVENTORY_UPDATED: 'INVENTORY_UPDATED',
  INVENTORY_SYNC_ERROR: 'INVENTORY_SYNC_ERROR',
  WEBHOOK_ERROR: 'WEBHOOK_ERROR',
} as const;

export type NotificationTypeValue = (typeof NotificationType)[keyof typeof NotificationType];
